// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9VWeKXNOqiBk-jQNUUeYl4R5HwFfo5PA',
    appId: '1:978205454969:web:cb5e5ee5aa26d057f11aa8',
    messagingSenderId: '978205454969',
    projectId: 'hoon-e7f3c',
    authDomain: 'hoon-e7f3c.firebaseapp.com',
    databaseURL: 'https://hoon-e7f3c-default-rtdb.firebaseio.com',
    storageBucket: 'hoon-e7f3c.appspot.com',
    measurementId: 'G-LH47LX6JDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMLdJk7rufFO92vvJCzJOWef0MRoZHIsw',
    appId: '1:978205454969:android:430db7a8b39f3433f11aa8',
    messagingSenderId: '978205454969',
    projectId: 'hoon-e7f3c',
    databaseURL: 'https://hoon-e7f3c-default-rtdb.firebaseio.com',
    storageBucket: 'hoon-e7f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHILizaM14hPcqVj5KzesOshF10fjPB7I',
    appId: '1:978205454969:ios:f089f5003e12a002f11aa8',
    messagingSenderId: '978205454969',
    projectId: 'hoon-e7f3c',
    databaseURL: 'https://hoon-e7f3c-default-rtdb.firebaseio.com',
    storageBucket: 'hoon-e7f3c.appspot.com',
    iosBundleId: 'com.hoon.auctionstoref',
  );
}
